# Load Data
# pre-processing and selection

In [1]:
import pandas as pd

df = pd.read_csv('Data/HeartAtackRisk_Data.csv')
print(df.head())

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  


In [2]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [3]:
import numpy as np
x = np.asarray(df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh', 'exng', 'caa']])
x

array([[ 63,   1,   3, ..., 150,   0,   0],
       [ 37,   1,   2, ..., 187,   0,   0],
       [ 41,   0,   1, ..., 172,   0,   0],
       ...,
       [ 68,   1,   0, ..., 141,   0,   2],
       [ 57,   1,   0, ..., 115,   1,   1],
       [ 57,   0,   1, ..., 174,   0,   1]], dtype=int64)

In [4]:
y = np.asarray(df['output'])
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# train/test

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=34)
print("train shape: ", x_train.shape , y_train.shape)
print("test shape: ", x_test.shape , y_test.shape)

train shape:  (242, 10) (242,)
test shape:  (61, 10) (61,)


In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Modeling
we have four model to train this dataset
and then we choose the better one
1. **KNN**
2. **Decision Tree**
3. **Logistic Regression**
4. **SVM**

## 1. KNN Model

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(26)
knn = knn.fit(x_train, y_train)
yhat = knn.predict(x_test)
print(yhat)

[1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1]


In [8]:
from sklearn import metrics
print("KNN Accuracy: ", metrics.accuracy_score(y_test,yhat))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, yhat)
print(cm)

KNN Accuracy:  0.9016393442622951
[[22  5]
 [ 1 33]]


In [10]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Ks = 40
mean_acc = np.zeros((Ks-1))

for n in range(1, Ks):
    neigh = KNeighborsClassifier(n_neighbors = n).fit(x_train, y_train)
    yhat = neigh.predict(x_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

print( "the best Accuracy:", mean_acc.max(), "is for k = ", mean_acc.argmax()+1)

the best Accuracy: 0.9016393442622951 is for k =  26


## 2. Decision Tree

In [11]:
from sklearn.tree import DecisionTreeClassifier

drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)

In [12]:
drugTree = drugTree.fit(x_train,y_train)
yhat2 = drugTree.predict(x_test)

In [13]:
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, yhat2))
cm1 = confusion_matrix(y_test, yhat2)
print(cm1)

DecisionTrees's Accuracy:  0.8360655737704918
[[21  6]
 [ 4 30]]


## 3. Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.1, solver='liblinear').fit(x_train,y_train)

yhat3 = LR.predict(x_test)

yhat_prob = LR.predict_proba(x_test)

In [15]:
print("Logistic Regression Accuracy: " ,metrics.accuracy_score(y_test, yhat3))
cm2 = confusion_matrix(y_test, yhat3)
print(cm2)

Logistic Regression Accuracy:  0.8688524590163934
[[22  5]
 [ 3 31]]


## 4. SVM

In [16]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train, y_train)

yhat4 = clf.predict(x_test)
yhat4[0:5]

array([1, 0, 0, 1, 1], dtype=int64)

In [17]:
print("SVM Accuracy: " ,metrics.accuracy_score(y_test, yhat4))
cm4 = confusion_matrix(y_test, yhat4)
print(cm4)


SVM Accuracy:  0.8524590163934426
[[22  5]
 [ 4 30]]
