# Load Data
# pre-processing and selection

In [1]:
import pandas as pd

df = pd.read_csv('Data/HeartAtackRisk_Data.csv')
print(df.head())

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  


In [2]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [3]:
import numpy as np
x = np.asarray(df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh', 'exng', 'caa']])
x

array([[ 63,   1,   3, ..., 150,   0,   0],
       [ 37,   1,   2, ..., 187,   0,   0],
       [ 41,   0,   1, ..., 172,   0,   0],
       ...,
       [ 68,   1,   0, ..., 141,   0,   2],
       [ 57,   1,   0, ..., 115,   1,   1],
       [ 57,   0,   1, ..., 174,   0,   1]], dtype=int64)

In [4]:
y = np.asarray(df['output'])
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# train/test

In [5]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(x).transform(x.astype(float))
X[0:5]

array([[ 0.9521966 ,  0.68100522,  1.97312292,  0.76395577, -0.25633371,
         2.394438  , -1.00583187,  0.01544279, -0.69663055, -0.71442887],
       [-1.91531289,  0.68100522,  1.00257707, -0.09273778,  0.07219949,
        -0.41763453,  0.89896224,  1.63347147, -0.69663055, -0.71442887],
       [-1.47415758, -1.46841752,  0.03203122, -0.09273778, -0.81677269,
        -0.41763453, -1.00583187,  0.97751389, -0.69663055, -0.71442887],
       [ 0.18017482,  0.68100522,  0.03203122, -0.66386682, -0.19835726,
        -0.41763453,  0.89896224,  1.23989692, -0.69663055, -0.71442887],
       [ 0.29046364, -1.46841752, -0.93851463, -0.66386682,  2.08204965,
        -0.41763453,  0.89896224,  0.58393935,  1.43548113, -0.71442887]])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=34)
print("train shape: ", x_train.shape , y_train.shape)
print("test shape: ", x_test.shape , y_test.shape)

train shape:  (242, 10) (242,)
test shape:  (61, 10) (61,)


# Modeling
we have four model to train this dataset
and then we choose the better one
1. **KNN**
2. **Decision Tree**
3. **Logistic Regression**
4. **SVM**

## 1. KNN Model

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(32)
knn = knn.fit(x_train, y_train)
yhat = knn.predict(x_test)
print(yhat)

[1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1]


In [15]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, knn.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test,yhat))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, yhat)
print(cm)

Train set Accuracy:  0.7892561983471075
Test set Accuracy:  0.9016393442622951
[[23  4]
 [ 2 32]]


In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Ks = 40
mean_acc = np.zeros((Ks-1))

for n in range(1, Ks):
    # تمرین مدل برای هر K
    neigh = KNeighborsClassifier(n_neighbors = n).fit(x_train, y_train)
    yhat = neigh.predict(x_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

print( "بهترین دقت:", mean_acc.max(), "در مقدار K=", mean_acc.argmax()+1)
plt.show()

بهترین دقت: 0.9016393442622951 در مقدار K= 32
